### ISSUE TITLE
Not working for PC Version

### ISSUE THREAD

**Issue by TheGoodCook** [lehieugch68/Nikke-NKAB-Decrypter#1]
Tried using the code given however nothing seems to happen even after compiling. The Window simply just opens and shuts.

**Comment by ByteFun** [comment]
> Tried using the code given however nothing seems to happen even after compiling. The Window simply just opens and shuts.

DragAndDrop directory with files on 'Nikke-NKAB-Decrypter.exe' and check files in dir again. You have UnityFS assets (decrypted)

**Comment by lehieugch68** [comment]
It was originally a console app, but I added a GUI to make it easier to use. Note that it will only decrypt files with NKAB signatures, you will need to use [AssetStudio](https://github.com/Perfare/AssetStudio) or UABE to extract the decrypted files.
