### ISSUE TITLE
Container paths are encrypted

### ISSUE THREAD

**Issue by PackageInstaller** [lehieugch68/Nikke-NKAB-Decrypter#3]
Thank you for your hard work. The program successfully decrypted the assets, but when I imported them into AssetStudio, I noticed that the container path has been replaced with characters resembling a hash. Is there a way to restore the original path?🤔

![image](https://github.com/lehieugch68/Nikke-NKAB-Decrypter/assets/80018096/1a838d17-cf37-42a2-b923-19f2ef12f61b)

**Comment by lehieugch68** [comment]
Container ≠ file name. 
You can right click -> Show original file.

**Comment by PackageInstaller** [comment]
I believe there might be a misunderstanding. What I meant is that I would like to export the Spine animations using the container path, as it would make them appear more organized and orderly.
